<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="57398" started-at="2020-02-18T09:51:52 BRT" finished-at="2020-02-18T09:52:50 BRT">
    <groups>
    </groups>
    <test name="Default test" duration-ms="57398" started-at="2020-02-18T09:51:52 BRT" finished-at="2020-02-18T09:52:50 BRT">
      <class name="br.com.rsinet.hub_tdd.testes.Cadastro">
        <test-method status="PASS" signature="extendReport()[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542]" name="extendReport" is-config="true" duration-ms="89" started-at="2020-02-18T09:51:52 BRT" finished-at="2020-02-18T09:51:52 BRT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- extendReport -->
        <test-method status="PASS" signature="iniciaTeste()[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542]" name="iniciaTeste" is-config="true" duration-ms="9515" started-at="2020-02-18T09:51:52 BRT" finished-at="2020-02-18T09:52:02 BRT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- iniciaTeste -->
        <test-method status="PASS" signature="testeDeCadastroFalha()[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542]" name="testeDeCadastroFalha" duration-ms="10163" started-at="2020-02-18T09:52:02 BRT" finished-at="2020-02-18T09:52:12 BRT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testeDeCadastroFalha -->
        <test-method status="PASS" signature="finalizaTeste(org.testng.ITestResult)[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542]" name="finalizaTeste" is-config="true" duration-ms="632" started-at="2020-02-18T09:52:12 BRT" finished-at="2020-02-18T09:52:13 BRT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testeDeCadastroFalha status=SUCCESS method=Cadastro.testeDeCadastroFalha()[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalizaTeste -->
        <test-method status="PASS" signature="iniciaTeste()[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542]" name="iniciaTeste" is-config="true" duration-ms="8889" started-at="2020-02-18T09:52:13 BRT" finished-at="2020-02-18T09:52:21 BRT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- iniciaTeste -->
        <test-method status="FAIL" signature="testeDeCadastroSucesso()[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542]" name="testeDeCadastroSucesso" duration-ms="27115" started-at="2020-02-18T09:52:21 BRT" finished-at="2020-02-18T09:52:49 BRT">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Cadastro efetuado com sucesso! did not expect to find [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Cadastro efetuado com sucesso! did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at br.com.rsinet.hub_tdd.testes.Cadastro.testeDeCadastroSucesso(Cadastro.java:102)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testeDeCadastroSucesso -->
        <test-method status="PASS" signature="finalizaTeste(org.testng.ITestResult)[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542]" name="finalizaTeste" is-config="true" duration-ms="566" started-at="2020-02-18T09:52:49 BRT" finished-at="2020-02-18T09:52:49 BRT">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=testeDeCadastroSucesso status=FAILURE method=Cadastro.testeDeCadastroSucesso()[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalizaTeste -->
        <test-method status="PASS" signature="finalizaExtendReport()[pri:0, instance:br.com.rsinet.hub_tdd.testes.Cadastro@5a1c0542]" name="finalizaExtendReport" is-config="true" duration-ms="404" started-at="2020-02-18T09:52:49 BRT" finished-at="2020-02-18T09:52:50 BRT">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- finalizaExtendReport -->
      </class> <!-- br.com.rsinet.hub_tdd.testes.Cadastro -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
